### ISSUE TITLE
When recovering files with the Metadata Analyzer some files have junk names

### ISSUE THREAD

**Issue by tdijital** [aerosoul94/FATXTools#2]
It seemed to only happen when there's one file in a chunk and they had filenames such as B, !, @, and 3

If it helps when running the Metadata Analyzer the log reported many invalid cluster indexes.

**Comment by aerosoul94** [comment]
I improved the metadata analyzer a bit if you would like to try it again. I improved its performance so it should run much quicker (~15 minute analysis was improved to 1 minute) and I made some changes to the tests it performs to validate dirents. If you could test it out again under your environment, that'd be great. Thanks!

**Comment by tdijital** [comment]
That solved my issue and the metadata analysis runs significantly quicker!
