### ISSUE TITLE
Dirents with names containing the character 0x59 are not recognized

### ISSUE THREAD

**Issue by burninrubber0** [aerosoul94/FATXTools#23]
Any dirent with a name containing a capital Y (0x59) are not displayed at all in Recovery View, and FATXTools does not recover these files. This applies to both directories and files. All other files in the directory are recognized and recover fine. Gaps in the offsets are visible where dirents containing this character have been skipped.

I'm not able to provide an example at the moment, but it should be reproducible elsewhere. Edit any image to use this character in a dirent and it won't display.

**Comment by aerosoul94** [comment]
FAIL. Nice catch!
https://github.com/aerosoul94/FATXTools/blob/de05bd5b283ed4590f2f06599aea7f97e08a8a75/FATX/Analyzers/MetadataAnalyzer.cs#L21

**Comment by aerosoul94** [comment]
It should be fixed with this commit.  Thanks a lot! I tested by manually setting "Y" and running metadata analyzer.
![image](https://user-images.githubusercontent.com/12718188/88444931-36ded700-cde5-11ea-93d8-ddb32c857377.png)
