### ISSUE TITLE
Alpha xbox harddisk

### ISSUE THREAD

**Issue by CodeAsm** [aerosoul94/FATXTools#28]
Im trying to help someone recover files from an actual alpha xbox. Could ask, willing to test and recreate a harddisk image. Lets asume for now they dont wanna share the image. Would adding xbox alpha harddisk support be tricky? The earliest recoverys installed basicly windows 2000, so i asume it would be fat32 or ntfs, but after this it turned into fatx at some point.

Im curious and going to find time soon to figure out what version his alpha 1 runs.  Maybe adding support isnt too hard if ms dint changed much after fatx got made, just the final location of the partition header or something changes due to nomore mbr?

**Comment by aerosoul94** [comment]
Hey @CodeAsm, I've added a new commit (f8b6842) to add support for some earlier FATX file system. Let me know if it helps!

**Comment by CodeAsm** [comment]
Awesome. I haven't had contact with said person lately, but i might be able to test on some dummy images. Unless thats what youve been doing aswell 🤭😉☺️ ill let you know if i know more. Also, hi on discord.

**Comment by aerosoul94** [comment]
Closed in #30
